//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Commits struct {
	ID                   *int32 `sql:"primary_key"`
	CommitMessage        *string
	GitDiffCommand       *string
	GitDiffCommandOutput *string
	ExcludeFiles         *string
	DateCreated          *time.Time
}
