//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Diff struct {
	ID                 *string `sql:"primary_key"`
	Diff               *string
	DateCreated        *time.Time
	DiffStructuredJSON *string
	Model              *string
	AiProvider         *string
	Prompts            *string
}
