//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type UserSettings struct {
	ID                     *string `sql:"primary_key"`
	ModelSelection         *string
	ExcludeFiles           *string
	UseConventionalCommits *bool
	DateCreated            *time.Time
}
